### ISSUE TITLE
Rollershutter-Icons in OpenHAB are inverse

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab#5]
Bugreport from forum:
"Rollladensteuerung und Update des Status funktioniert.
Eine gaaaanz kleine Anmerkung: Das Icon zeigt den Zustand invers an; also Rollladen zu, wenn auf und umgekehrt."

100 means closed, 0 means open, see https://github.com/ollie-dev/openhab/tree/1.6/distribution/openhabhome/webapps/images/rollershutter*.png

**Comment by daniellueddecke** [comment]
From my point of view this is not a bug. A binding cannot control the mapping of icons. OpenHAB defines a roller shutter is fully closed at 100%. RWE defines that a roller shutter is fully opened at 100%.
We could only change this behavior by inverting the roller shutter states (e.g. Notification coming in saying the roller shutter is at 80% would be mapped to 20%). In my opinion this is not correct and my be irritating to users when RWE applications and openHAB are not in sync.

As a workaround we could provide an inverted icon set. When defining items user could then use the icon name "<rollershutterINV>" to get correct icons. I've already testes this and it is working. Please let me know if this would be okay...

**Comment by ollie-dev** [comment]
Good point. I think there are reasons for both variants. An option could be to make it configurable...

I suppose I'll ask the OpenHAB guys in the KNX forum, how other bindings manage it. I think it is good to be aligned.

**Comment by ollie-dev** [comment]
In z-wave binding, it is configurable per item:
"invert_state=true can be used to invert the state of a multilevel switch command class. eg this can be used to reverse the direction of a rollershutter."

See https://github.com/openhab/openhab/wiki/Z-Wave-Binding. Sound like a solution - what do you think?

**Comment by daniellueddecke** [comment]
Sounds like a plan.
