### ISSUE TITLE
Support for MotionDetectionSenor

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab#6]

**Comment by daniellueddecke** [comment]
Do we have any Notification-XML regarding this?

**Comment by ollie-dev** [comment]
Yes an no. I checked it, but no notifications were sent. So its like with a PushButtonSensor - we have no direct access to them. It can only be done by configuration then, e.g. by using a GenericActuator in the RWE client that is bound to a motionDetectionSensor. :(
