### ISSUE TITLE
Lowering setpoint temperature not possible?

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab#8]
- Zudem habe ich beobachtet, dass Smarthome zwar ein inkrementelles Hochsetzen der Temperatur in 0.5 Schritten zulässt
2015-05-28 18:29:26.117 [INFO ] [runtime.busevent ] - TemperaturWohnzimmerSoll state updated to 8.5
jedoch ein Runtersetzen nicht ausführt, bzw. der Befehl wird von OpenHab nicht bearbeitet.

**Comment by daniellueddecke** [comment]
What commands are used to decrease the temperature by 0.5?

**Comment by ollie-dev** [comment]
I'll check this one on my installation later.

**Comment by ollie-dev** [comment]
Checked and generally works on my installation. Setting temperatures only can be a bit weird if you e.g. press the up button 5 times quick to adjust temperature by 2.5 degrees. Then the updates are to fast in a row. I'm not sure, if this is a binding problem...
