### ISSUE TITLE
RST Room temperature setpoints do not update properly in openhab

### ISSUE THREAD

**Issue by profigriller** [ollie-dev/openhab#9]
I created a event profile to change setpoint for 5 RSTs. Usually only 4 updates are shown, sometimes only 3 but never all 5. Log files have been sent to ollie

**Comment by daniellueddecke** [comment]
Just for my understanding: the event profile is created in openHAB or in the RWE software itself?

**Comment by ollie-dev** [comment]
He made an event profile in RWE client: if a variable is set to true, 5 thermostats are set to 16 degrees, if set to false 5 thermostats are set to 15 degrees.

I checked the logfiles and see the following behaviour in notifications.xml:
1. switch to false: 3 notifications to 15 degrees
2. switch to true: 4 notifications to 16 degrees
3. switch to false: 5 notifications to 15 degrees
4. switch to true: 4 notifications to 16 degrees

Seems to be a notifications problem on RWE side - if there is no notification, we cannot react. @profigriller, what do you see in RWE client? do all setpoint temperatures go to the wanted value?

**Comment by profigriller** [comment]
The profile is build within RWE software. I see what you mean.  I also use a php client script and this gets updated properly.
I'll do more test, check notifications.xml and note down how the other clients behave.

**Comment by profigriller** [comment]
I did more tests and found that for 5 changes
- RWE software does not update properly (1 value not updated)
- openhab updates even worse (2 values not updates even though 4 events are in the notification.xml)


The only thing which works always is my PHP skript based on the php library. But I think this works differently


2015-06-01 17:57:44 - ZV16 state updated to ON 
Kommando Raum1, Raum2, Raum3, Bad, Kueche auf 16.0
Anzeige in SH Silverlight: Raum2, Raum3, Bad, Kueche auf 16.0; Raum1 bleibt auf AUS
Anzeige im PHP Skript korrekt (16.0)
Anzeige in Openhab : Raum2, Raum3, Kueche auf 16.0; Raum1, Bad bleiben auf AUS

Seems I can't attach log files here. So I'll send them to Ollie by mail again.

**Comment by ollie-dev** [comment]
I tested the same with my three thermostats. Unfortunately the same result: Sometimes three notifications come and everything is fine, but sometimes only two notifications come through and the values in OpenHAB are wrong. Looks like a bug in RWE client? However, RWE client is upto date, if I switch the variable out of OH. So there seems to be all notifications. I'll sniff this, as soon as my windows-pc is ready.
